name: My First Workflow

on: push # trigger event

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo # latest is v6 at the time of writing this file
          uses: actions/checkout@v6 #https://github.com/marketplace/actions/checkout
        - name: Welcome message
          run: echo "My first GitHub Actions job"

        - name: List files
          run: ls
        
        - name: Read file
          run: cat README.md
